applications/juego/urls.py
from django.urls import path

from . import views

app_name = "juego_app"

urlpatterns = [
    path(
        'list', 
        views.JuegoListView.as_view(),
        name='juego',
    ),
]

applications/panel/urls.py
from django.urls import path

from . import views

app_name = "panel_app"

urlpatterns = [
    path(
        '', 
        views.Panel.as_view(),
        name='index',
    ),
    
]

applications/user/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='login',
    ),
    path(
        'logout/', 
        views.LogOutView.as_view(),
        name='logout',
    ),
]

juegoinfo/urls.py
from django.contrib import admin
from django.urls import path ,re_path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.juego.urls')),
    re_path('', include('applications.panel.urls')),
    re_path('', include('applications.user.urls')),
]

applications/juego/models.py
from django.db import models

from .managers import JuegoManager
class Juego(models.Model):
    """Model definition for Juego."""

    name = models.CharField("nombre del juego", max_length=40)

    description = models.TextField(
        'Descripcion de la categoria',
        blank=True,
    )
    price = models.FloatField(default=0)

    image = models.URLField( blank=True)

    link_url = models.URLField( blank=True)

    objects = JuegoManager()
    class Meta:
        

        verbose_name = 'Juego'
        verbose_name_plural = 'Juegos'

    def __str__(self):
        return str(self.id) + '-' + self.name

applications/panel/models.py
from django.db import models

# Create your models here.

applications/user/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    full_name = models.CharField("Nombre Completo", max_length=50)
    email = models.EmailField(unique=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'

    objects = UserManager()

    def __str__(self):
        return str(self.id) + '-' + self.full_name

applications/juego/forms.py
from django import forms

from .models import Juego 

class FormJuego(forms.ModelForm):
  
    class Meta:
        model = Juego

        fields=('__all__')

applications/user/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña'
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'email',
            'full_name',
            'dni',
        )
        

  
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')
            

class LoginForm(forms.Form):
    email = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.TextInput(
            attrs={
                
                'placeholder': 'Correo Electronico',  
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

            

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data

applications/juego/views.py
from django.shortcuts import render

from django.urls import reverse_lazy, reverse
# Create your views here.

from django.views.generic import (
    View,
    CreateView,
    ListView
)

from .forms import FormJuego
from .models import Juego



class JuegoListView(ListView):
    model = Juego
    template_name = "juego/list.html"

applications/panel/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import  TemplateView


from applications.juego.models import Juego


class Panel(TemplateView):
    template_name = "panel/index.html"

    
    
    def get_context_data(self, **kwargs):
        context = super(Panel, self).get_context_data(**kwargs)
        kword = self.request.GET.get("kword", '')
        context['juegos'] = Juego.objects.search_juego(kword)
        

        return context

    

applications/user/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic import (
    View,
    CreateView
)

from django.views.generic.edit import (
    FormView
)

from .forms import (
    UserRegisterForm,
    LoginForm
)
from .models import User
# 


class UserRegisterView(FormView):
    template_name = 'user/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:login')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name=form.cleaned_data['full_name'],       
        )
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)

class LoginUser(FormView):
    template_name = 'user/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('panel_app:index')

    def form_valid(self, form):
        user = authenticate(
            #con el autenticate se verifica que exista este usuario
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password'],
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)

class LogOutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'panel_app:index'                
            )
        )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-MX">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <title>{% block title %}{% endblock title %}</title>
  {% block css %}{% endblock css %}
</head>
<body>
  
  {% block content %}
  {% endblock content %}

  {% block js %}

  {% endblock js %}
  
</body>

</html>

templates/include/header.html
{% extends "base.html" %}
{% load  static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/include/header.css' %}">

{% endblock css %}

{% block content %}
<header class="header">
  <div class="container">
    <a href="{% url 'panel_app:index' %}"><img class="logo" src="{% static 'img/logo.png' %}" alt="logo teclado"></a>
    <div class="container__buscador">
      <form method="GET" class="form">
        <button class="lupa" type="submit"><img src="{% static 'img/search.png' %}" alt=""></button>
        <input type="text" id="kword" name="kword" placeholder="Buscar..">
      </form>
    </div>
    <nav class="navegation">
      <button class="hamburger" id="hamburger">  <img src="{% static 'img/menu_bar.png' %}" alt="">   </button>
      <ul class="nav-ul" id="nav-ul">
        {% if  user.is_anonymous %}
        <li><a href="{% url 'users_app:login' %}">Iniciar Sesion</a></li>
        <li><a href="{% url 'users_app:register' %}">Registrarse</a></li>
        {% else %}
        <li>perfil</li>
        <ul>
          <li> <a href="{% url 'users_app:logout'  %}">Cerrar Sesion</a></li>
        </ul>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>

{% endblock content %}

{% block js %}
<script src="{% static 'js/header.js' %}"></script>
{% endblock js %}

templates/juego/list.html
{% extends "base.html" %}

{% load  static %}
{% block title %}
Juegos
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/panel/index.css' %}">
{% endblock css %}

{% block content %}
{% include "include/header.html" %}
<div class="container_index">
    <div class="card">
        <div class="image"><img src="{{ juego.image.url }}" alt=""></div>
        <div class="info">
            <h2>{{object.name}} </h2>
            
        </div>
    </div>
</div>





{% endblock content %}

templates/panel/index.html
{% extends "base.html" %}

{% load  static %}
{% block title %}
Juegos
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/panel/index.css' %}">
{% endblock css %}

{% block content %}
{% include "include/header.html" %}
<div class="container_index">

    {% for juego in juegos  %}
    <div class="card">
        <div class="image"><img src="{{ juego.image }}" alt=""></div>
        <div class="info">
            <div class="titulo"> 
                <h2>{{juego.name}} </h2>
            </div> 
            <div class="description"> 
                <h4>{{juego.description | truncatechars:70}} </h4>
            </div>
            <div class="precio">
                <h3>${{juego.price}} </h3>
                <a class="steam" href="{{ juego.link_url }}"><img src="{% static 'img/steam.png' %}" alt=""></a>
            </div>
        </div>
        
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/user/login.html
{% extends "base.html" %}

{% load  static %}
{% block title %}
Log in
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/user/sesion.css' %}">
{% endblock css %}

{% block content %}
{% include "include/header.html" %}
<div class="cotainer__all">
    <div class="container_sesion">
        <form method="POST" class="card"> {% csrf_token %}
            <input type="email" placeholder="Email" value="{{ email }}" name="email">
            <input type="password" placeholder="Contraseña" value="{{ password }}" name="password">
    
            {% for error in form.non_field_errors %}
            <p>
                {{ error|escape }}
            </p>
            {% endfor %}
            
            <button type="submit"> Log in</button>
        </form>
    </div>
</div>

{% endblock content %}

templates/user/register.html
{% extends "base.html" %}

{% load  static %}
{% block title %}
Log in
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/user/sesion.css' %}">
{% endblock css %}

{% block content %}
{% include "include/header.html" %}
<div class="cotainer__all">
    <div class="container_sesion">
        <form method="POST" class="card"> {% csrf_token %}
            <input type="text" placeholder="Nombre" value="{{ full_name }}" name="full_name">
            <input type="email" placeholder="Email" value="{{ email }}" name="email">
            <input type="password" placeholder="Contraseña" value="{{ password1 }}" name="password1">
            <input type="password" placeholder="Repetir Contraseña" value="{{ password2 }}" name="password2">
            {% for error in form.password2.errors %}
            <p>
                {{ error|escape }}
            </p>
            {% endfor %}

            <button type="submit"> Create acount</button>
        </form>
    </div>
</div>

{% endblock content %}